### ISSUE TITLE
Is this a joke? Piercing howl has been broken for over 1 month now

### ISSUE THREAD

**Issue by nacsdale** [LightsHope/issues#792] opened 2018-08-09 02:24 UTC
Piercing howl is only applying to one target and it should aoe slow. Has been reported already and no progress ofc.

**Comment by Sabre142** [comment] 2018-08-09 06:00
Fix it yourself.

**Comment by simonmathay** [comment] 2018-08-12 14:45
Can confirm. Really annoying!

**Comment by ratkosrb** [comment] 2018-08-12 20:08
Duplicate of https://github.com/LightsHope/issues/issues/604

**Closed as completed by ratkosrb** 2018-08-12 20:08 UTC
