### ISSUE TITLE
Booty Bay Auction House bugs

### ISSUE THREAD

**Issue by lomsac** [LightsHope/issues#1151] opened 2018-12-14 15:02 UTC
First of all, thank you for taking the time to report this issue.

Please note that the bug tracker does not accept reports on account or character
issues that are unrelated to the server's development. You should open a ticket
in game and wait for the response of a gamemaster. They may redirect you to this
bug tracker if they believe there's a server issue that they cannot help you
with.

Before writing your report, please do read and consider the following points to
increase the quality of your report.

Search the issue tracker for open and closed issues before opening a new
issue. You may be able to contribute additional facts by commenting on
existing issues instead of adding extra noise in a separate issue.
http://www.wowhead.com/ and http://db.vanillagaming.org/ are not valid sources
for quests, items etc., instead, please use archived versions of
http://wow.allakhazam.com or http://www.thottbot.com through
https://archive.org/.
Validate the date and time of the archived sources to a certain patch. The
patch release dates can be found on the corresponding WoWWiki article, as
found at http://wowwiki.wikia.com/wiki/Category:World_of_Warcraft_patches.
Videos are valid if and only if the footage contains a timestamp or
information that confirms the time it was recorded. Date of upload is NOT
valid and does not confirm when it was shot.

Once you've read this message, delete it and write your report below.

--

Write your report here

Booty Bay Auction House bugs

In an attempt to sell a Fine Longbow on my alliance character, to my friends horde character, with the BB AH. There was no item showing up.

A GM told me to ensure in this report that all addons are disabled and i am not shadowmuted.
The GM tried checking the AH out himself. For him there was two other Fine Longbows on the AH, but noone of them was sold by my character. Also these other bows were not displayed for me or my friend.
![wow1](https://user-images.githubusercontent.com/45878493/50010379-95ad5f00-ffb9-11e8-8749-a8fa373fe75e.png)
![wow2](https://user-images.githubusercontent.com/45878493/50010385-98a84f80-ffb9-11e8-8445-ad2bc4dc5571.png)

**Comment by Holyfrogg** [comment] 2018-12-15 22:23
This is not a bug. There is a timer on the Auction house before items show up to players on a different IP address. This was added some time back on Elysium to combat the issue of players using macros to snipe items being transferred between factions.

Wait a while, then it should show up.

**Closed as completed** 2019-04-27 13:01 UTC
