### ISSUE TITLE
Green Lens of Stamina - Northdale

### ISSUE THREAD

**Issue by Shamatix** [LightsHope/issues#1259] opened 2019-03-20 12:31 UTC
How come you've managed to fuck certain items up on Northdale and not Lightshope? For instance Green Lens of Stamina aint possible what so ever on Northdale, but it was on Lights hope?

"Green Lens item can no longer call Stamina as one of its random properties. Existing Green Lens have not been changed." - patch 1.3
But we aint on 1.3, far from

**Comment by Shivsproket** [comment] 2019-03-20 15:24
What is the issue here?

**Comment by Shamatix** [comment] 2019-03-20 17:36
The issue is Green Lens of Stamina isnt able to be crafted on Northdale and never has been, while it should.
On Lights hope this wasnt an issue at all and Green Lens of Stamina was obtainable but on Northdale it never has been obtainable thus far.

**Comment by Shamatix** [comment] 2019-03-21 14:10
> 
> 
> What is the issue here?

Any chance to have a look at it?:)

**Comment by Gamemechanicwow** [comment] 2019-03-21 21:37
Ehh... Northdale is on patch 1.9, so its working as intended.

**Comment by Shamatix** [comment] 2019-03-26 12:06
The thing is it was NEVER able to drop from engineering on northdale! Try take a look on players on Northdale I bet you that you will never ever be able to find anyone who has crafted this head and it has never been on AH on Northdale either.

**Comment by Gamemechanicwow** [comment] 2019-03-26 13:30
A fix has been submitted to the core, so the item will have the appropiate suffixes during the early patches.

https://github.com/lh-server/core/pull/179

**Comment by Shamatix** [comment] 2019-03-28 16:50
Thanks

**Closed as completed** 2019-04-27 12:29 UTC

**Comment by bladezLH** [comment] 2019-04-27 12:30
Will never be attainable on Northdale.
