### ISSUE TITLE
SFK - Can't get past Fenrus door

### ISSUE THREAD

**Issue by ghost** [LightsHope/issues#857] opened 2018-08-26 08:35 UTC
The door after defeating Fenrus the Devourer in Shadowfang Keep will not open.

If I remember correctly, the order of events should be that once defeating Fenrus, Archmage Arugal appears above you, casts down a spell, and summons some mobs. Once the mobs are defeated the door should open.

Archmage Arugal does appear, does his spell, but mobs do not appear, so you can't kill them to proceed.

**Comment by ratkosrb** [comment] 2018-08-27 04:03
Duplicate of https://github.com/LightsHope/issues/issues/397

**Closed as completed** 2018-08-27 04:03 UTC
